{{ if and .Values.distributedLogs.enabled .Values.distributedLogs.create }}
apiVersion: stackgres.io/v1
kind: SGDistributedLogs
metadata:
  name: {{ .Values.cluster.distributedLogs.sgDistributedLogs }}
  {{- if and .Release.IsInstall .Values.cluster.create }}
  annotations:
    "helm.sh/hook": pre-install
    "meta.helm.sh/release-name": {{ .Release.Name }}
    "meta.helm.sh/release-namespace": {{ .Release.Namespace }}
  {{- if .Values.cluster.version }}
    stackgres.io/operatorVersion: "{{ .Values.cluster.version }}"
  {{- end }}
  labels:
    app.kubernetes.io/managed-by: "Helm"
  {{- end }}
spec:
  persistentVolume:
    size: {{ quote .Values.cluster.distributedLogs.persistentVolume.size }}
    {{- with .Values.cluster.distributedLogs.persistentVolume.storageClass }}
    {{- if eq "-" . }}
    storageClass: ""
    {{- else }}
    storageClass: {{ . }}
    {{- end }}
    {{- end }}
  {{- with .Values.distributedLogs.postgresServices }}
  postgresServices:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.cluster.distributedLogs.scheduling }}
  scheduling:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.distributedLogs.metadata }}
  metadata:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.nonProductionOptions }}
  nonProductionOptions:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{ end }}
