{{ if and (eq .Values.kind "SGShardedCluster") .Values.cluster.create }}
apiVersion: stackgres.io/v1alpha1
kind: SGShardedCluster
metadata:
  name: {{ .Release.Name }}
  {{- if .Values.cluster.version }}
  annotations:
    stackgres.io/operatorVersion: "{{ .Values.cluster.version }}"
  {{- end }}
spec:
  type: {{ quote .Values.shardedCluster.type }}
  database: {{ quote .Values.shardedCluster.database }}
  postgres:
    {{- toYaml .Values.cluster.postgres | nindent 4 }}
  {{- with .Values.shardedCluster.postgresServices }}
  postgresServices:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.cluster.replication }}
  replication:
    mode: {{ quote .mode }}
    {{- with .syncInstances }} 
    syncInstances: {{ . }}
    {{- end }}
  {{- end }}
  {{- with .Values.cluster.metadata }}
  metadata:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- if or .Values.shardedCluster.configurations .Values.cluster.configurations.backups }}
  configurations:
    {{- if not .Values.cluster.disableBackups }}
    {{- with .Values.cluster.configurations.backups }}
    {{- if .sgObjectStorage }}
    backups:
    - {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- end }}
    {{- end }}
    {{- with ((.Values.shardedCluster.configurations).credentials) }}
    credentials:
      {{- toYaml . | nindent 6 }}
    {{- end }}
  {{- end }}
  {{- with .Values.cluster.initialData }}
  initialData:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  coordinator:
    instances: {{ .Values.cluster.instances }}
    configurations: 
      sgPostgresConfig: {{ quote .Values.cluster.configurations.sgPostgresConfig }}
      sgPoolingConfig: {{ quote .Values.cluster.configurations.sgPoolingConfig }}
    sgInstanceProfile: {{ quote .Values.cluster.sgInstanceProfile }}
    {{- with .Values.cluster.managedSql }}
    managedSql:
    {{- with .continueOnSGScriptError }}
      continueOnSGScriptError: {{ . }}
    {{- end }}
    {{- if .scripts }}
      scripts:
      - sgScript: {{ $.Release.Name }}-scripts
    {{- end }}
    {{- end }}
    pods:
      persistentVolume:
        size: {{ quote .Values.cluster.pods.persistentVolume.size }}
        {{- if .Values.cluster.pods.persistentVolume.storageClass }}
        {{- if eq "-" .Values.cluster.pods.persistentVolume.storageClass }}
        storageClass: ""
        {{- else }}
        storageClass: {{ quote .Values.cluster.pods.persistentVolume.storageClass }}
        {{- end }}
        {{- end }}
    {{- with ((.Values.shardedCluster.coordinator).replication) }}
    replication:
      {{- toYaml . | nindent 6 }}
    {{- end }}
  shards:
    clusters: {{ .Values.shardedCluster.shards.clusters }}
    instancesPerCluster: {{ .Values.shardedCluster.shards.instancesPerCluster }}
    configurations: 
      sgPostgresConfig: {{ quote .Values.cluster.configurations.sgPostgresConfig }}
      sgPoolingConfig: {{ quote .Values.cluster.configurations.sgPoolingConfig }}
    sgInstanceProfile: {{ quote .Values.cluster.sgInstanceProfile }}
    {{- with .Values.shardedCluster.shards.managedSql }}
    managedSql:
    {{- with .continueOnSGScriptError }}
      continueOnSGScriptError: {{ . }}
    {{- end }}
    {{- if .scripts }}
      scripts:
      - sgScript: {{ $.Release.Name }}-scripts
    {{- end }}
    {{- end }}
    pods:
      persistentVolume:
        size: {{ quote .Values.cluster.pods.persistentVolume.size }}
        {{- if .Values.cluster.pods.persistentVolume.storageClass }}
        {{- if eq "-" .Values.cluster.pods.persistentVolume.storageClass }}
        storageClass: ""
        {{- else }}
        storageClass: {{ quote .Values.cluster.pods.persistentVolume.storageClass }}
        {{- end }}
        {{- end }}
    {{- with .Values.shardedCluster.shards.replication }}
    replication:
      {{- toYaml . | nindent 6 }}
    {{- end }}
  {{- if .Values.distributedLogs.enabled }}
  {{- with .Values.cluster.distributedLogs }}
  distributedLogs:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- end }}
  {{- with .Values.cluster.prometheusAutobind }}
  prometheusAutobind: {{ . }}
  {{- end }}
  {{- with .Values.nonProductionOptions }}
  nonProductionOptions:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
