resources:
# All RBAC will be applied under this service account in
# the deployment namespace. You may comment out this resource
# if your operator will use a service account that exists at
# runtime. Be sure to update RoleBinding and ClusterRoleBinding
# subjects if changing service account names.
- service_account.yaml
- role.yaml
- role_binding.yaml
- editor_role.yaml
- viewer_role.yaml
