# permissions for end users to edit sgconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: sgconfig-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: stackgres
    app.kubernetes.io/part-of: stackgres
    app.kubernetes.io/managed-by: kustomize
  name: sgconfig-editor-role
rules:
- apiGroups:
  - stackgres.io
  resources:
  - *
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - stackgres.io
  resources:
  - sgconfigs/status
  verbs:
  - get
