apiVersion: v2
name: stackgres-cluster
description: StackGres Cluster
version: "1.19.0-SNAPSHOT"
appVersion: "1.19.0-SNAPSHOT"
keywords:
  - stackgres
  - postgresql
  - postgres
  - cluster
  - stack
  - opinionated
home: https://stackgres.io
sources:
  - https://gitlab.com/ongresinc/stackgres
maintainers: 
  - name: OnGres Inc.
    email: info@ongres.com
    url: https://ongres.com
icon: https://gitlab.com/uploads/-/system/project/avatar/12584701/logo-stackgres.png?width=64
kubeVersion: "1.18.0-0 - 1.34.x-0"
deprecated: false
