apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  name: stackgres.v${VERSION}
  namespace: placeholder
  annotations:
    description: |
      The most advanced Postgres Enterprise Platform.
      Fully Open Source.
    alm-examples: '[]'
    capabilities: Deep Insights
    operatorhub.io/ui-metadata-max-k8s-version: "$(yq -r '.kubeVersion|match("^[^ ]+ - ([^.]+\\.[^.]+)\\..*$").captures[0].string' "$PROJECT_PATH"/stackgres-k8s/install/helm/stackgres-operator/Chart.yaml).999"
    categories: Database
    repository: https://gitlab.com/ongresinc/stackgres
    containerImage: quay.io/stackgres/operator:${IMAGE_TAG}
spec:
  displayName: StackGres
  provider:
    name: OnGres
    url: https://ongres.com
  version: "${VERSION}"
  minKubeVersion: "$(yq -r '.kubeVersion|match("^([^.]+\\.[^.]+)\\..*$").captures[0].string' "$PROJECT_PATH"/stackgres-k8s/install/helm/stackgres-operator/Chart.yaml).0"
  maturity: stable
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
$(
  for CRD in $(grep -vxF SGBackupConfig.yaml config/crd/bases/index.txt)
  do
    if ! yq -r '.[].kind' config/crd/bases/crd-descriptors.yaml | grep -qxF "${CRD%.yaml}"
    then
      >&2 echo "Can not find ${CRD%.yaml} in config/crd/bases/crd-descriptors.yaml"
      exit 1
    fi
  done
  yq -r '.[].kind' config/crd/bases/crd-descriptors.yaml \
    | while read KIND
      do
        yq -y --arg KIND "$KIND" 'map(select(.kind == $KIND))' \
          config/crd/bases/crd-descriptors.yaml
        yq -y -s --arg ROOT_KEY "spec" -f extract-descriptors-from-openapi.jq \
          config/crd/bases/"$KIND".yaml config/crd/bases/"$KIND".descriptors.yaml \
          | sed 's/^/  /'
        yq -y -s --arg ROOT_KEY "status" -f extract-descriptors-from-openapi.jq \
          config/crd/bases/"$KIND".yaml config/crd/bases/"$KIND".descriptors.yaml \
          | sed 's/^/  /'
      done \
    | sed 's/^/    /'
)
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
$(
  if [ "$CREATE_CONVERSION_WEBHOOKS" = true ]
  then
    cat << EOF
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: true
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
EOF
 else
    cat << EOF
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: true
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
EOF
 fi
)
  keywords:
  - postgresql
  - postgres
  - database
  - sql
  - rdbms
  - open source
  - ongres
  links:
  - name: StackGres Web
    url: https://stackgres.io
  - name: StackGres Docs
    url: https://stackgres.io/doc
  maintainers:
  - email: stackgres@ongres.com
    name: OnGres
  labels:
    operatorframework.io/arch.amd64: supported
    operatorframework.io/arch.arm64: supported
    operatorframework.io/os.linux: supported
  relatedImages:
  - image: quay.io/ongres/kubectl:v1.28.8-build-6.31
    name: kubectl_1_28_8
  - image: gcr.io/kubebuilder/kube-rbac-proxy:v0.13.0
    name: kube-rbac-proxy_0_13_0
  - image: quay.io/stackgres/operator:${VERSION}
    name: stackgres-operator
  - image: quay.io/stackgres/restapi:${VERSION}
    name: stackgres-restapi
  - image: quay.io/stackgres/admin-ui:${VERSION}
    name: stackgres-admin-ui
  - image: quay.io/stackgres/jobs:${VERSION}
    name: stackgres-jobs
  description: |
$(
  sed 's/^/    /' config/manifests/bases/stackgres.clusterserviceversion.description.txt
)
  icon:
  - base64data: |
      PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCA1MDAg
      NTAwIiBzdHlsZT0iZW5hYmxlLWJhY2tncm91bmQ6bmV3IDAgMCA1MDAgNTAwIiB4bWw6c3BhY2U9
      InByZXNlcnZlIj4KICAgIDxzd2l0Y2g+CiAgICAgICAgPGc+CiAgICAgICAgICAgIDxwYXRoIHN0
      eWxlPSJmaWxsOiM0MmE4YzgiIGQ9Im01LjIgMjczLjcgMTEwLjcgMTI2LjhoMjY4LjJsMTEwLjct
      MTI2LjgtMTEwLjctMTI2LjhIMTE1Ljl6Ii8+CiAgICAgICAgICAgIDxwYXRoIHN0eWxlPSJmaWxs
      OiM0MjZkODgiIGQ9Ik0xMTUuOSA0MDAuNWgyNjguNHY1Ni40SDExNS45eiIvPgogICAgICAgICAg
      ICA8cGF0aCBzdHlsZT0iZmlsbDojNDI4YmI0IiBkPSJNMTE1LjkgNDU2LjggNS4yIDMzMHYtNTYu
      M2wxMTAuNyAxMjYuOHoiLz4KICAgICAgICAgICAgPHBhdGggc3R5bGU9ImZpbGw6IzE2NjU3YyIg
      ZD0iTTM4NC4xIDQ1Ni44IDQ5NC44IDMzMHYtNTYuM0wzODQuMSA0MDAuNXoiLz4KICAgICAgICAg
      ICAgPHBhdGggZD0iTTQ2NS43IDI1My40YzAtNDctOTYuNi04NS4yLTIxNS43LTg1LjJTMzQuNCAy
      MDYuMyAzNC40IDI1My40czk2LjUgODUuMiAyMTUuNiA4NS4yIDIxNS43LTM4LjIgMjE1LjctODUu
      MnoiIHN0eWxlPSJmaWxsOiMzOWI1NGEiLz4KICAgICAgICAgICAgPHBhdGggZD0iTTQ2NS43IDI1
      My40YzAgNDctOTYuNiA4NS4yLTIxNS43IDg1LjJTMzQuNCAzMDAuNCAzNC40IDI1My40djQ2Ljlj
      MTQuOSA0MS4zIDEwNi41IDg1LjIgMjE1LjYgODUuMnMyMDAuOC00My45IDIxNS43LTg1LjJ2LTQ2
      Ljl6IiBzdHlsZT0iZmlsbDojMDA5MjQ1Ii8+CiAgICAgICAgICAgIDxwYXRoIHN0eWxlPSJmaWxs
      OiNmMmM2M2YiIGQ9Ik0xNi4zIDE3OC42IDI1MCAzMTQuMWwyMzMuOC0xMzUuNUwyNTAgNDMuMnoi
      Lz4KICAgICAgICAgICAgPHBhdGggc3R5bGU9ImZpbGw6I2YyYjEzNiIgZD0iTTE2LjMgMTc4LjZ2
      NTIuOEwyNTAgMzY2Ljl2LTUyLjh6Ii8+CiAgICAgICAgICAgIDxwYXRoIHN0eWxlPSJmaWxsOiNm
      MmExMzAiIGQ9Ik00ODMuOCAxNzguNiAyNTAgMzE0LjF2NTIuOGwyMzMuOC0xMzUuNXoiLz4KICAg
      ICAgICAgICAgPHBhdGggc3R5bGU9ImZpbGw6I2ZmNzEyNCIgZD0ibTY4IDIxMi40IDM2NC4xLTUz
      LTkyLjQtMTA2eiIvPgogICAgICAgICAgICA8cGF0aCBzdHlsZT0iZmlsbDojZDkzZDFiIiBkPSJt
      NjggMjEyLjQgMzY0LjEtNTN2NDcuOEw2OCAyNjAuMXoiLz4KICAgICAgICA8L2c+CiAgICA8L3N3
      aXRjaD4KPC9zdmc+Cg==
    mediatype: image/svg+xml
