apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-extensions-cache
  namespace: {{ .Release.Namespace }}
data:
  nginx.conf: |
    pid             /var/run/nginx.pid;
    events{
    }
    http {
      include       /etc/nginx/mime.types;
      default_type  application/octet-stream;
      
      log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';
      
      access_log  /var/log/nginx/access.log  main;
      
      sendfile        on;
      
      keepalive_timeout  65;
      
      include /etc/nginx/conf.d/*.conf;
    }
  stackgres-operator-extensions-cache.conf: |
    server {
      server_name  localhost;
      
      listen       8080;
      root   /opt/app-root/src;
      
      location / {
        try_files $uri =404;
      }
    }
